services:
  - type: web
    name: trybeforebuy
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-137.0.7151.55/chrome-linux64/chrome