services:
  - type: web
    name: trybeforebuy
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18